version: '3.8'
  
services:

    service-db:
        container_name: postgres-server
        image: postgres:14.7-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mypass
        ports:
          - "5432:5432"
        volumes:
          - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
          - db-data:/var/lib/postgresql/data
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4:7
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: 1@1.com
          PGADMIN_DEFAULT_PASSWORD: mypass
        ports:
          - "5050:80"
        depends_on:
          - service-db
        volumes:
            - pgadmin-data:/var/lib/pgadmin
            

    ###### MongoDB

    mongodb:
        image: mongodb
        container_name: mongodb
        build: 
            context: ./db
            dockerfile: Dockerfile
        hostname: mongodb
        ports:
            - 27017:27017
        command: --bind_ip_all --quiet
        logging:
            driver: none
            
    minio:
        image: quay.io/minio/minio
        command: server /data --console-address ":9090"
        restart: always
        ports:
          - 9000:9000
          - 9090:9090
        volumes:
          - ~/minio/data:/data
        environment:
          - MINIO_ROOT_USER=admin
          - MINIO_ROOT_PASSWORD=adminadmin

volumes:
  db-data:
  pgadmin-data:
        